### ISSUE TITLE
Not receive notification iOS

### ISSUE THREAD

**Issue by tuantvk** [Pushwoosh/pushwoosh-react-native-plugin#119]
i use code example
```js
import Pushwoosh from 'pushwoosh-react-native-plugin';

Pushwoosh.init({ 
    "pw_appid" : "YOUR_PUSHWOOSH_APP_ID" , 
    "project_number" : "YOUR_FCM_SENDER_ID" 
});
Pushwoosh.register();

// this event is fired when the push is received in the app
DeviceEventEmitter.addListener('pushReceived', (e: Event) => {
  console.warn("pushReceived: " + JSON.stringify(e));
  // shows a push is received. Implement passive reaction to a push, such as UI update or data download.
});

// this event is fired when user clicks on notification
DeviceEventEmitter.addListener('pushOpened', (e: Event) => {
  console.warn("pushOpened: " + JSON.stringify(e));
  // shows a user tapped the notification. Implement user interaction, such as showing push details
});
```
and check device on server PW
```sh
https://cp.pushwoosh.com/json/1.3/checkDevice
```
body request
```json
{
    "request": {
        "application": "XXXXX",
        "hwid": "XXXX-XXXX-XXXX" // i replaced hw
    }
}
```
data return here
```js
{
    "status_code": 200,
    "status_message": "OK",
    "response": {
        "exist": true,
        "push_token_exist": true
    }
}
```

but when i push notify, on ios 13.6.1 not receive notification. i have re-check device on server PW data return push_token_exist false.
```json
{
    "status_code": 200,
    "status_message": "OK",
    "response": {
        "exist": true,
        "push_token_exist": false
    }
}
```

**Comment by tuantvk** [comment]
previously it still works, but when i rebuild new app (not update PW) it not working

**Comment by wfhm** [comment]
@tuantvk it looks like a token is deleted from our database after sending a push. This usually happens when APNS responds with an error (like DeviceTokenNotForTopic). It could indicate that your build is signed with a provisioning profile that does not match your app's configuration in the Pushwoosh Control Panel. Please check that the provisioning profile type (development or distribution) matches the gateway used in the **Configure** tab (Sandbox or Production correspondingly) and that the app's bundle ID matches the ID of your push certificate.

Please let me know about the results.

**Comment by tuantvk** [comment]
I have check configure PW and my team changed it.
