### ISSUE TITLE
[IOS] Access push notification from notification center, triggered "pushOpened" & "pushReceived" event

### ISSUE THREAD

**Issue by jason-ong** [Pushwoosh/pushwoosh-react-native-plugin#14]
If I access push notification from notification center,

In IOS,
both "pushOpened" & "pushReceived" will be triggered.

In android,
"pushOpened" will be triggered only.

Is it a bug?

**Comment by wfhm** [comment]
Hi,

This is an intended behavior. Due to iOS limitations, your app cannot track received pushes when it is not in foreground, and a `pushReceived` callback will only fire when you bring your application to foreground via opening a push notification. `pushOpened` callback will fire as well after that.

When receiving a push in foreground, `pushReceived`fires immediately, and `pushOpen` fires only when you open a notification in the Notification Center. 

You can find a bit more detailed information on the flow in the thread below:

https://stackoverflow.com/questions/14616261/receiving-push-notifications-while-in-background
