### ISSUE TITLE
[Question]: No visible @interface for 'Pushwoosh' declares the selector 'getUserId'

### ISSUE THREAD

**Issue by DanushkaPerusinghe** [Pushwoosh/pushwoosh-react-native-plugin#167]
### Documentation

- [X] I've checked the guide, but I didn't find the information I needed there.

### Question

<img width="685" alt="Screenshot 2024-09-07 at 1 41 06 PM" src="https://github.com/user-attachments/assets/d6e797db-2bbf-4ab6-af2a-2912cfdfd412">

"pushwoosh-react-native-plugin": "^6.1.32",
"react": "18.2.0",
"react-native": "0.71.7",

iOS build failed due to above error. 
Do I need to do pod update?
Any idea about above issue.

**Comment by enginseer-dev** [comment]
Hello @DanushkaPerusinghe! Yes, please update the core SDK in the project, execute `cd ios && pod install && cd ..` or `pod update` in your terminal in the project's directory. Let us know the results!

**Comment by DanushkaPerusinghe** [comment]
Hi @enginseer-dev,

Thanks for the reply. 
I did the pod update and got below error.

<img width="561" alt="Screenshot 2024-09-08 at 10 40 02 PM" src="https://github.com/user-attachments/assets/48cbed1c-7c63-4a35-86b6-c13fdbfeb8c2">

Is there anything need to do?

**Comment by DanushkaPerusinghe** [comment]
Oh now it worked. Perviously it try to clone 6.7.0 remote branch. And now it cloned 6.6.0 branch and installed successfully. 

<img width="542" alt="Screenshot 2024-09-08 at 10 46 50 PM" src="https://github.com/user-attachments/assets/583244fd-314c-453d-9365-ce3482d3a23b">

**Comment by enginseer-dev** [comment]
@DanushkaPerusinghe,

Oh, it seems the iOS core SDK 6.7.0 had some critical issues and was rolled back to 6.6.1 just recently: https://github.com/Pushwoosh/pushwoosh-ios-sdk/releases

So, please try to
1. [Clear React Native caches](https://help.pushwoosh.com/hc/en-us/articles/16842837689757-Clear-project-caches-to-resolve-various-build-errors#h_01HPY4XAFWH4EMN01BNS8V5XN0)
2. `pod repo update`
3. (optional, since pod repo update should resolve it) add the v 6.6.1 to the podfile explicitly.

**Comment by enginseer-dev** [comment]
Glad to hear the issue was resolved, @DanushkaPerusinghe.
I'll just leave the information here in case it helps anyone.

**Comment by DanushkaPerusinghe** [comment]
> Glad to hear the issue was resolved, @DanushkaPerusinghe. I'll just leave the information here in case it helps anyone.

Thank you so much for the support. 😀
