### ISSUE TITLE
iOS subscriber problem

### ISSUE THREAD

**Issue by Sangrene** [Pushwoosh/pushwoosh-react-native-plugin#42]
Hi !

After adding this plugin to our application, it seems to work well on Android but on iOS we are observing a strange behaviour.

We run the app in release mode (to try the notification we must do it in release), the device get registered and we can see an iOS subscriber. The thing is that if we close the app, we loose the registered device on Pushwoosh dashboard and can't send the push notification.

Anyone got a clue on how to solve that ?

**Comment by wfhm** [comment]
@Sangrene 

This is definitely not an expected behavior. Since further investigation potentiall requires knowledge of your Pushwoosh account name, notification IDs and other sensitive information, may I ask you to create a ticket to our Support Team at help@pushwoosh.com? Please also add a link to this issue in your email.

**Comment by wfhm** [comment]
@Sangrene did you have a chance to communicate with our Support team? Is this issue still persistent?

**Comment by Sangrene** [comment]
It seems like by releasing the update on the App store, we noticed that the push notifications were working as expected. Closing the issue.

**Comment by NikolayDonev** [comment]
What update are you referencing? I am having the exact same issue where my iOS subscribers are gone after a minute without being unsubscribed.

**Comment by Sangrene** [comment]
Hey @NikolayDonev , I meant OUR app update. This problem seems to solve itself on production.

**Comment by nadhir-falta** [comment]
@NikolayDonev Were you able to solve this ? I'm seeing the exact issue as you.

**Comment by Tilenozz** [comment]
@Sangrene , the issue seems still alive. I have tested is testfligth and the trouble persist. Am i suppose to public on APP store to check if notification on IOS work ?? how is it possible ??

I'm working with React native plugin. On Android got no trobule even on simulator.

This is the situation on Ios ... 

1 Step - Register the device by Api - It work and release the token
2 Step  - Check on website , and search by token...found it ..

![image](https://user-images.githubusercontent.com/54805850/212783190-29c00d97-3924-4aa1-b52d-4017c1690adf.png)

3 Step - Send a standard notification by site - Push notification - One time Push - Done
![image](https://user-images.githubusercontent.com/54805850/212783300-067f119f-9895-44ff-b453-fc82c0e274d2.png)

4 Step - Check how many devices reaches ( Statistic -> Channel ) --- 2 ( seems work ) 
![image](https://user-images.githubusercontent.com/54805850/212783987-fcc66e58-f676-4a0d-a021-fa53cdd2db62.png)

5 Step - check Device .... No notify received 
6 Step - Re-Check user by token ---- 0 
![image](https://user-images.githubusercontent.com/54805850/212784046-9dd79fe2-f259-4166-9af8-70f605e24de3.png)

![image](https://user-images.githubusercontent.com/54805850/212784076-692e6c6e-f0d0-446a-8532-f5d651834293.png)

Can u investigate a bit more deeply ?
If u need more info , don t esistate to contact me
Thanks

**Comment by wfhm** [comment]
@Tilenozz 
This usually happens when application configuration in Pushwoosh Control Panel does not match the configuration of your project (most likely, the uploaded provisioning profile does not match). Could you please contact our support team via this form - https://www.pushwoosh.com/contact-us/ - and provide them with the account details so they could assist you further?
