### ISSUE TITLE
pushOpened event not fired on iOS

### ISSUE THREAD

**Issue by Exilz** [Pushwoosh/pushwoosh-react-native-plugin#6]
```javascript
DeviceEventEmitter.addListener('pushOpened', _pushHandler);
```
works on Android, but I can't get it to work on iOS. I still have to use the deprecated
```javascript
Pushwoosh.onPushOpen(_pushHandler);
```

if I want my handler to work. Registering to push still works and tapping the notification properly opens the app.

Thanks for the help.

**Comment by DimanAM** [comment]
```js
DeviceEventEmitter.addListener('pushOpened', _pushHandler);
```

Should work on react-native@0.38.0 (used in sample project) and latest 0.39.2 version.

**Comment by franverona** [comment]
I'm having the same issue even with the solution proposed by @Exilz :(

**Comment by Exilz** [comment]
@franverona I had to downgrade the plugin, I forgot to say that. `1.2.5` if I recall correctly.
I'm pretty sure the event isn't working properly with the latest version.

**Comment by franverona** [comment]
Still not working (on iOS; on Android works). Here is my code (I'm using `1.2.5` because the latest version isn't working either):

```
import React from 'react';
import { 
  AppRegistry, 
} from 'react-native';

import App from './app';

AppRegistry.registerComponent('MyApp', () => App);

var _pushHandler = function (pushData) {
  console.log(pushData);
};

var Pushwoosh = require('pushwoosh-react-native-plugin');

Pushwoosh.init({ 'pw_appid' : '1234-5678' , 'project_number' : '1234567' });
Pushwoosh.register(
      (token) => {
        console.log('✓ Registered for pushes');,
      (error) => {
        console.error('Failed to register: ' + error);
);

Pushwoosh.onPushOpen(_pushHandler);
```

**Comment by franverona** [comment]
Any news about this?

**Comment by franverona** [comment]
Hello Pushwoosh? :(

**Comment by wfhm** [comment]
Small public update: the issue is being investigated via private support channel with @franverona, so as soon as we figure out something we will update this thread.

**Comment by franverona** [comment]
After almost two months of emails (15 emails and 4 different people looking for a solution), we decided to change our push notification provider because we weren't seeing any light at the end of the tunnel. In case that someone wants a working alternative using React Native, feel free to contact me for more information. I wish you all the best Pushwoosh. 

-Fran

**Comment by wfhm** [comment]
Hi @franverona!
It is sad to hear that you've decided to stop being our customer.
To sum up - the issue wasn’t reproducible on our Sample app. We were trying to investigate further with the code snippets provided but weren’t able to continue without full reproducer and console logs from the actual devices, which were not provided to us upon request.
We have also unsuccessfully tried to reach you on January, 31 and February, 09.
Please feel free to contact us again if you decide to go further with investigation.

**Comment by franverona** [comment]
Hi @wfhm,

Yes, you're absolutly right. You reached me on both dates and I honestly didn't answer you guys because we were involved in several projects (not only the one that I'd mentioned on the email). Maybe it was some incompatibility between Pushwoosh and some library, maybe an Android or iOS version, etc. There was so many factors and our client was pushing us so hard that we decided to change our provider.

Nothing personal, of course. Tech support was great, but deadlines were killing us and we needed a quicker solution (our client only wanted push notification, not advanced metrics, so our current provider is just fine for this). Maybe in a future if we need advanced features like you have, we'll switch again.

Thanks!
