### ISSUE TITLE
Gradle build fails with 5.19.3

### ISSUE THREAD

**Issue by EugeneDraitsev** [Pushwoosh/pushwoosh-react-native-plugin#88]
step to reproduce:

1. Upgrade plugin from 5.18.1 -> 5.19.3
2. Run gradle build
3. Get an error: 

```
In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.0.0
, 1.0.1]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: com.pushwoosh:pushwoosh:5.19.3 -> android.arch.work:work-runtime@[1.0.0, 1.0.1], but work-runtime ve
rsion was 1.0.1.
```

**Comment by wfhm** [comment]
@EugeneDraitsev,

This was already fixed in our native SDK (5.19.5 version), the plugin will be updated shortly.

Meanwhile you can try to manually change the SDK version to 5.19.5 in the plugin’s build.gradle in node_modules:

https://github.com/Pushwoosh/pushwoosh-react-native-plugin/blob/4aa8ced3e513f6025d3d6c38f07d96a05f39187c/src/android/build.gradle#L42

**Comment by EugeneDraitsev** [comment]
@wfhm thanks for fast responses, I can wait for 5.9.5 release

**Comment by nagad814** [comment]
when is the expected release date for 5.19.5?

**Comment by jacobcabantomski-ct** [comment]
@nagad814 https://github.com/Pushwoosh/pushwoosh-react-native-plugin/releases/tag/5.19.5
